### ISSUE TITLE
`medfateland` still expecting meteo dataframes with row.names

### ISSUE THREAD

**Issue by MalditoBarbudo** [emf-creaf/medfateland#2]
`medfateland` still expects and **needs** dates as row names of meteo data.frames.
This not only conflicts with any tibble (no row names can be set in tibbles), but also makes very complicated pipe in an interpolated object from `meteoland 2.0.0` as meteo to internal functions like `.model_spatial_day` and `.f_spatial_day` as in the LFC apps engines.

I'm sure there are other functions that sill expect *"old"* meteo dataframes with rownames, as well calls to deprecated functions from `meteoland 2.0.0`. This need to be revised.

**Comment by miquelcaceres** [comment]
Today I worked on `medfate` and `medfateland` to allow dates as columns or row names in meteo data.frames. I also made the functions of `medfateland` to accept lists of interpolator objects from `meteoland 2.0.0`, which should facilitate simulations.
